version: '3'

services:
  sakura:
    container_name: sakura
    build: ./SakuraBot
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: nachi
      POSTGRES_PASSWORD: nachi
    restart: unless-stopped
  proxy:
    container_name: nginx
    build: ./Nginx
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - sakura
    links:
      - sakura
    restart: always
  # pgadmin:
  #   container_name: pgadmin
  #   image: fenglc/pgadmin4
  #   environment:
  #     DEFAULT_USER: nachi@nachi.com
  #     DEFAULT_PASSWORD: nachi
  #   volumes:
  #      - /data/pgadmin:/root/.pgadmin
  #   ports:
  #     - "5050:5050"
  #   restart: unless-stopped