version: '3'

services:
  sakura:
    build: ./
    ports:
      - 5000:80
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: nachi
      POSTGRES_PASSWORD: nachi
    restart: unless-stopped
  pgadmin:
    links:
      - postgres:postgres
    image: fenglc/pgadmin4
    environment:
      DEFAULT_USER: nachi@nachi.com
      DEFAULT_PASSWORD: nachi
    volumes:
       - /data/pgadmin:/root/.pgadmin
    ports:
      - "5050:5050"
    restart: unless-stopped